server:
  port: 9090

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///pinxixi_mall?useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456789
  devtools:
    livereload:
      #热部署
      enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    # 抛出404异常
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    # 时区
    time-zone: GMT+8
  # redis配置
  redis:
    port: 6379
    host: 127.0.0.1

# JWT配置
jwt:
  # 秘钥
  secret: pinxixi2022666
  # token请求头
  tokenHeader: Authorization
  # token前缀
  tokenPrefix: Bearer
  # token过期时间 单位 秒
  expiration: 3600
  # 不需要认证的路径
  excludePaths: /admin/login, /client/register, /client/login, /error, /swagger-ui/**, /swagger-resources/**, /v3/api-docs


# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

