server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///pinxixi_mall?useUnicode=true
    username: root
    password: 123456789
  devtools:
    livereload:
      enabled: false #热部署
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true # 抛出404异常
  web:
    resources:
      add-mappings: false

mybatis:
  mapper-locations: classpath:mapper/*.xml

# 项目配置
pinxixi:
    jwt:
      header_auth: Authorization
      exclude: /admin/login,/client/register,client/login # 不需要token的url
